build:
	go build -o myapp .

clean:
	rm -f myapp

followTest:
	./myapp -s "i'll follow you as long as you are following me"

test1: 
	./myapp -s "follower brings bunch of questions"

test2: 
	./myapp -s "                                                                        "

test3: 
	./myapp -s "i'll not 4 above"

test42:
	./myapp -s "The answer to this is very simple. I sat at my desk, stared into the garden and thought:42 will do. I typed it out. End of story"
